/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    public static void main(String[] args) throws Exception {

        llm chat = new llm("llama3.2:1b");

        String prompt =
        "Please, write for me a cpp program for tictactoe game. " +
        "It shoul be a console application. " +
        "The console should draw the board with the ASCII graphics. " +
        "Use characters 'X', 'O', '+', '-' and '|' for it. " +
        "User always have a first turn. " +
        "He enters the number 1-9 to make a turn. " +
        "1 is for bottom left cell, " +
        "2 for bottom middle cell, " +
        "3 for bottom right cell, " +
        "4 for middle left cell, " +
        "5 for center cell, " +
        "6 for middle right cell, " +
        "7 for top left cell, " +
        "8 for top middle cell, " +
        "9 for top right cell, " +
        "'Q' needs to quit the game. " +
        "It should be a single-file source code. " +
        "Please, provide me the text of the program only. " +
        "Don't use any formatting in your answer.";

        System.out.println("Creating initial program.");
        String program = chat.ask(prompt);
        file.write("tictactoe.cpp", program);
        chat.close();

        System.out.println("Fixing build errors");
        int counter = 0;
        while (true) {
            String build_errors = cmd.run("g++", "tictactoe.cpp", "-o", "tictactoe");
            if (build_errors.isEmpty()) { break; }
            System.out.println("iteration " + counter + "...");
            System.out.println(build_errors);
            counter++;

            prompt = "I have next program written in cpp:";
            prompt += "\n'''\n";
            prompt += program;
            prompt += "\n'''\n";
            prompt += "I tried to build it and got next errors:";
            prompt += "\n'''\n";
            prompt += build_errors;
            prompt += "\n'''\n";
            prompt += "Please, fix these errors and provide me the text of the";
            prompt += " fixed program. Answer with plain text only without any";
            prompt += "formatting and comments.";

            llm debug_chat = new llm("llama3.2:1b");
            program = debug_chat.ask(prompt);
            debug_chat.close();
            file.write("tictactoe.cpp", program);
        }

        System.out.println("Done, all build issues are fixed");
    }
}
